version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: atlas-postgres
    environment:
      POSTGRES_DB: atlas
      POSTGRES_USER: atlas
      POSTGRES_PASSWORD: atlas
    ports:
      - "5432:5432"
    volumes:
      - atlas_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U atlas -d atlas"]
      interval: 10s
      timeout: 5s
      retries: 5

  atlas:
    build:
        context: .
        dockerfile: Dockerfile-dev

    container_name: atlas-app
    ports:
      - "8081:8080"
      - "5005:5005"   # ðŸ‘ˆ DEBUG PORT
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/atlas
      SPRING_DATASOURCE_USERNAME: atlas
      SPRING_DATASOURCE_PASSWORD: atlas
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_JPA_SHOW_SQL: true
      SPRING_DOCKER_COMPOSE_ENABLED: false
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_LOCATIONS: "classpath:db/migration"
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
      SPRING_FLYWAY_BASELINE_VERSION: "0"
      SPRING_FLYWAY_BASELINE_DESCRIPTION: "Initial baseline"

 
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: pom.xml

volumes:
  atlas_pgdata:
