spring:
  application:
    name: atlas 
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/atlas}
    username: ${SPRING_DATASOURCE_USERNAME:atlas}
    password: ${SPRING_DATASOURCE_PASSWORD:atlas}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}
    locations: ${SPRING_FLYWAY_LOCATIONS:classpath:db/migration}
    baseline-on-migrate: ${SPRING_FLYWAY_BASELINE_ON_MIGRATE:true}
    baseline-version: ${SPRING_FLYWAY_BASELINE_VERSION:0}
    baseline-description: ${SPRING_FLYWAY_BASELINE_DESCRIPTION:Initial baseline}
    out-of-order: false
    validate-on-migrate: true
    mixed: false
    clean-disabled: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    org.flywaydb: DEBUG
    org.flywaydb.core: DEBUG
